### ISSUE TITLE
Demo Link 404 - Not Found (Missing)

### ISSUE THREAD

**Issue by geraldb** [hmfaysal/Jekyll-HMFAYSAL-Theme#1]
Hello, FYI: The  See demo at http://www.theevilgenius.tk is 404 - Not Found. Cheers.

**Comment by mushishi78** [comment]
@geraldb I put a demo here: [Jekyll-HMFAYSAL-Theme](http://jekyll-demos.github.io/Jekyll-HMFAYSAL-Theme/)

But, @hmfaysal it really wouldn't be much trouble. You just need to change to `gh-pages` branch and change the url in the `_config` to http://hmfaysal.github.io/Jekyll-HMFAYSAL-Theme/

**Comment by geraldb** [comment]
Thanks. Great. Cheers.

**Comment by hmfaysal** [comment]
Will do that, thanks @mushishi78
